apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-docker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-docker
  template:
    metadata:
      labels:
        app: python-docker
    spec:
      containers:
      - name: python-docker
        image: guysade4/python-docker:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000


---
apiVersion: v1
kind: Service
metadata:
  name: python-docker-service
spec:
  selector:
    app: python-docker
  type: LoadBalancer
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30500



